import 'word.dart';

class WordList {
  static final List<Word> validWords = [
    Word(word: 'MONEY'),
    Word(word: 'ASSET'),
    Word(word: 'STOCK'),
    Word(word: 'BONDS'),
    Word(word: 'LOANS'),
    Word(word: 'TRADE'),
    Word(word: 'SPEND'),
    Word(word: 'PRICE'),
    Word(word: 'VALUE'),
    Word(word: 'DEBTS'),
    Word(word: 'WAGES'),
    Word(word: 'COSTS'),
    Word(word: 'BUYER'),
    Word(word: 'OFFER'),
    Word(word: 'FUNDS'),
    Word(word: 'YIELD'),
    Word(word: 'GROSS'),
    Word(word: 'TRUST'),
    Word(word: 'SHARE'),
    Word(word: 'RATES'),
    Word(word: 'BILLS'),
    Word(word: 'CHECK'),
    Word(word: 'CHART'),
    Word(word: 'RATIO'),
    Word(word: 'TREND'),
    Word(word: 'HEDGE'),
    Word(word: 'AUDIT'),
    Word(word: 'VAULT'),
    Word(word: 'BRIBE'),
    Word(word: 'BONUS'),
    Word(word: 'LEASE'),
    Word(word: 'TAXES'),
    Word(word: 'PROXY'),
    Word(word: 'GRANT'),
    Word(word: 'LEGAL'),
    Word(word: 'RISKY'),
    Word(word: 'MERGE'),
    Word(word: 'BREAK'),
    Word(word: 'CRASH'),
    Word(word: 'CLAIM'),
    Word(word: 'PRIME'),
    Word(word: 'FLOAT'),
    Word(word: 'CHAIN'),
    Word(word: 'BLOCK'),
    Word(word: 'TOKEN'),
    Word(word: 'INDEX'),
    Word(word: 'QUOTE'),
    Word(word: 'ORDER'),
    Word(word: 'STORE'),
    Word(word: 'UNITS'),
    Word(word: 'QUOTA'),
    Word(word: 'STAKE'),
    Word(word: 'LIMIT'),
    Word(word: 'INPUT'),
    Word(word: 'GOODS'),
    Word(word: 'LABOR'),
    Word(word: 'SALES'),
    Word(word: 'WORTH'),
    Word(word: 'MACRO'),
    Word(word: 'BRAND'),
    Word(word: 'SCORE'),
    Word(word: 'SPENT'),
    Word(word: 'WAGER'),
    Word(word: 'BANKS'),
  ];
  static Word getRandomWord() {
    validWords.shuffle();
    return validWords.first;
  }
}
